services:
  - type: web
    name: baixarapidao-bot
    runtime: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PORT
        value: 10000
      - key: WEBHOOK_URL
        sync: false
